stages:
  - build
  - deploy
  - release

.only_changes: &changes_def
    changes:
      - Dockerfile
      - Makefile
      - lizmap-entrypoint.sh
      - "*.php"
      - "*.php.dist"

build:ltr:
  stage: build
  script:
    - make build deliver clean-all VERSION=3.2.6 VERSION_SHORT=3.2 RELEASE_TAG=ltr
  environment:
    name: snap
  only:
    <<: *changes_def
  except:
    - schedules
  artifacts:
    paths:
      - factory.manifest
  tags:
    - infrav3

build:nightly_ltr:
  stage: build
  script:
    - make build deliver clean VERSION=ltr-nightly LIZMAP_BRANCH=release_3_2
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: snap
  only:
    <<: *changes_def
    refs:
      - schedules
  artifacts:
    paths:
      - factory.manifest
  tags:
    - infrav3

build:release:
  stage: build
  script:
    - make build deliver clean-all VERSION=3.3.0 VERSION_SHORT=3.3 RELEASE_TAG=latest
  environment:
    name: snap
  only:
    <<: *changes_def
  except:
    - schedules
  artifacts:
    paths:
      - factory.manifest
  tags:
    - infrav3

build:nightly:
  stage: build
  script:
    - make build deliver clean VERSION=nightly LIZMAP_BRANCH=release_3_3
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: snap
  only:
    <<: *changes_def
    refs:
      - schedules
  artifacts:
    paths:
      - factory.manifest
  tags:
    - infrav3

build:dev:
  stage: build
  script:
    - make build deliver clean-all VERSION=dev LIZMAP_BRANCH=master
  environment:
    name: snap
  only:
    <<: *changes_def
    refs:
      - schedules
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - $HOME/bin/lzmservicectl update -C MUTU lizmap  --annotate="Updated image ($CI_COMMIT_SHORT_SHA)"
  environment:
    name: snap
  only:
    <<: *changes_def
  tags:
    - infrav3

release:ltr:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh lizmap-web-client-ltr
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: production
  dependencies:
    - build:ltr
  when: manual
  tags:
    - infrav3
  except:
    - schedules

release:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh lizmap-web-client
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh --clean
  environment:
    name: production
  dependencies:
    - build:release
  when: manual
  tags:
    - infrav3
  except:
    - schedules


